dependencies:
  - Uniswap/v3-periphery@1.0.0
  - Uniswap/v2-core@1.0.1
  - sbvegan/v2-periphery@latest
compiler:
  solc:
    remappings:
      - "@uniswap-v3-periphery=Uniswap/v3-periphery@1.0.0"
      - "@uniswap-v2-core=Uniswap/v2-core@1.0.1"
      - "@uniswap-v2-periphery=sbvegan/v2-periphery@latest"
dotenv: .env
networks:
  default: mainnet-fork
  mainnet-fork:
    infura: ${MAINNET_INFURA}
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    uniswap_router_v2: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    uniswap_factory_v2: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
  mainnet:
    infura: ${MAINNET_INFURA}
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    uniswap_router_v2: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    uniswap_factory_v2: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
wallets:
  from_key: ${PRIVATE_KEY}